Bus_Pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('transporter/', include('transporter.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from .views import *
from django.urls import path, include
from . import views as view

#from transporter.views import Create_Schedule_Trips
app_name = 'home'
urlpatterns = [
   path('',view.home, name="index"),
   path('c/',Create_Schedule_Trips, name="index22"),
   path('Student_Location/',view.Student_Location, name="Student_Location"),
   path('mydata2/',view.mydata2, name="mydata2"),
  
  

]

home/models.py
from django.db import models
from django.db.models import Q
from users.models import *
# Create your models here.
Gender = (
		('boy', 'boy'),
		('girl', 'girl'),
		
	)

def Path_Student_Avatar(instance,filename):
    

    return "student/%s/avataer/%s/avatar.jpeg"%(instance.id ,instance.name)



class is_NotNullManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(latitude__isnull=True).exclude(latitude__exact='')

class is_NullManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(latitude__isnull=False)

class Student(models.Model):
    name = models.CharField(max_length=200, null=True) 
    age = models.IntegerField( null=True) 
    gender = models.CharField(choices=Gender, default = 'boy' , max_length=10)
    guardian_numbber = PhoneNumberField(help_text= 'EXP : 966563481855' ,blank=True , null=True , default='966563481855')
    Guardians_id = models.ForeignKey(Profile, limit_choices_to={'role': 'Guardian'}, on_delete=models.DO_NOTHING , related_name='Students_Guardians', null=True , blank=True)
    address = models.CharField(max_length=2000, null=True,blank=True)
    address2 = models.CharField(max_length=2000, null=True,blank=True)
    latitude = models.CharField(max_length=200,blank=True, null=True)
    longitude = models.CharField(max_length=200,blank=True, null=True)
    avatar = models.FileField(upload_to=Path_Student_Avatar , default='media/Student/avataer/profile_av.jpg')
    assign_seats = models.BooleanField(default=False)
    objects = models.Manager()
    is_not_nool = is_NotNullManager()
    is_null = is_NullManager()
    def __str__(self):
         return self.name
    class Meta:
        ordering = ["-address"] 

home/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import *
from users.models import *
from transporter.views import *
import datetime
# Create your views here.
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@login_required(login_url='users:login')
def home(request):

    
    key = settings.GOOGLE_MAKER_API_KEY
    stu = Student.is_not_nool.all()
    stu_count = Student.objects.count()
    driver_count = Driver_Profile.objects.count()
    staff_count = Profile.objects.count()
    guardians_count = Profile.objects.count()
    print(stu_count)
   
    context = {
        'key':key,
        'stu':stu,
        'stu_count':stu_count,
        'driver_count':driver_count,
        'staff_count':staff_count,
        'guardians_count':guardians_count,
    }
    return render(request, 'home/home.html',context)


@login_required(login_url='users:login')
def Student_Location():
   
    result_list = list(Student.objects\
                .values('id',
                        'name', 
                        'latitude',
                        'longitude',
                        'avatar',
                        'gender',
                        'age',
                        ))

    return JsonResponse(list(result_list), safe=False)



from .SMS  import *
def save(self, *args, **kwargs):
        name = 'ngggg'
        text = '966563481855'
        Send_SMS(text , name )
        

def  end_sms(request):
   name = 'ngggg'
   text = '966563481855'
   Send_SMS(text , name )
   return JsonResponse('data')



def mydata2(request):
   
    result_list = list(Student.objects\
                .values('id',
                        'name', 
                        'latitude',
                        'longitude',
                        'avatar',
                        'gender',
                        'age',
                        ))

    return JsonResponse(list(result_list), safe=False)

home/templates/home/MapDirections_HomeToSchool.html
{% extends '_base.html' %}
{% load static %}
{% block content %}

<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<script type="text/javascript">
   
    function initMap() {
        const directionsService = new google.maps.DirectionsService();
        const directionsRenderer = new google.maps.DirectionsRenderer();
        const map = new google.maps.Map(document.getElementById("mapContainer"), {
            zoom: 13.5,
            center: { lat: 24.522383148639438, lng: 44.4186252342999 },
            mapTypeId: google.maps.MapTypeId.HYBRID ,
            disableDefaultUI: true, 
        });

        directionsRenderer.setMap(map);
        directionsRenderer.setPanel(document.getElementById("sidebar"));

  const control = document.getElementById("floating-panel");

  map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);

        {% for x in stu %}
        document.getElementById({{x.id}}).addEventListener("click", () => {
            addr =' {{x.address}}'
      calculateAndDisplayRoute(directionsService, directionsRenderer , addr );
    });
    {% endfor %}
 
        


    }


    function calculateAndDisplayRoute(directionsService, directionsRenderer , addr) {
        directionsService
            .route({
                origin: {
                    query: addr,
                },
                destination: {
                    query: document.getElementById("Schoole").value,
                },
                travelMode: google.maps.TravelMode.DRIVING,
                
            })
            .then((response) => {
                directionsRenderer.setDirections(response);
            })
            .catch((e) => window.alert("Directions request failed due to " + status));
    }

    window.initMap = initMap;

</script>

<section class="content ">
    <div class="block-header mt-6">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>App Widgets
                    <small>Welcome to Oreo</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-white btn-icon btn-round hidden-sm-down float-right m-l-10" type="button">
                    <i class="zmdi zmdi-plus"></i>
                </button>
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Oreo</a></li>
                    <li class="breadcrumb-item active">Widgets</li>
                    <li class="breadcrumb-item active">App</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <!-- start student list -->
        <div class="col-sm-12 col-md-12 col-lg-2">
            <div class="card current_progress">
                <div class="header">
                    <h2><strong>student</strong> list</small></h2>
                </div>

                <div class="body">
                    <div class="chat-widget">
                        <ul class="chat-scroll-list clearfix">
                            <li class="inbox-inner"> <a href="javascript:void(0)">
                                    <div class="inbox-item">

                                    </div>
                                </a>
                            </li>




                        </ul>
                        <ul class="chat-scroll-list clearfix">
                            <div class="body">
                                <ul class="list-unstyled activity">
                                    {% for x in stu %}
                                    <li id="{{ x.id }}">
                                        <a href="javascript:void(0)">
                                            <i class=""><img
                                                    src="{% if x.gender == 'girl' %} {% static 'assets/images/avatar_girl.jpeg' %}{% else %} {% static 'assets/images/avatar_boy.jpeg' %} {% endif %}"
                                                    class="rounded" style="width: 200px;" alt=""></i>
                                            <div class="info">
                                                <h6>{{x.name}} </h6>
                                                <small>{{x.gender |default:"--"}}</small>

                                            </div>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </ul>
                    </div>
                   
                </div>
            </div>
        </div>
        <!-- end student list -->
        <!-- start map -->
        <div class="col-sm-12 col-md-12 col-lg-10">
            <div class="card">
                <div class="header">
                    <h2><strong>Map</strong> Bus Trip</h2>
                  
                </div>
                <div class="body">
                   
                    <div class="row clearfix"> 
                        <div class="col-sm-12 col-md-12 col-lg-10">
                            <div id="mapContainer"></div>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-2">
                           
                                <div class="chat-widget">
                                    <ul class="chat-scroll-list clearfix">
                                        <div class="body " style="padding: 0%;">
                                            <ul class="list-unstyled activity">
                                                <div id="sidebar">
                                            </ul>
                                        </div>
                                    </ul>
                                </div>
                            
                        </div>

                    </div>
                      
                       
                            

                  
                </div>
            </div>
        </div>
        <!-- end map -->
    </div>
    <select id="Schoole" style="visibility: hidden;">
        <option value="HF7F+PC7 جامعة شقراء, Al Rabwah, Al Duwadimi 17472" style="visibility: hidden;"></option>

    </select>

    
   
</section>

<!-- 
      The `defer` attribute causes the callback to execute after the full HTML
      document has been parsed. For non-blocking uses, avoiding race conditions,
      and consistent behavior across browsers, consider loading using Promises.
      See https://developers.google.com/maps/documentation/javascript/load-maps-js-api
      for more information.
      -->

<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCClagirEbcFsHwY7YipA6CeqEPyT7ciRo&callback=initMap&v=weekly&language=ar&region=SA"
    defer></script>

{% endblock content %}

home/templates/home/MapDirections_SchoolToHome.html
{% extends '_base.html' %}
{% load static %}
{% block content %}

<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<script type="text/javascript">
   
    function initMap() {
        const directionsService = new google.maps.DirectionsService();
        const directionsRenderer = new google.maps.DirectionsRenderer();
        const map = new google.maps.Map(document.getElementById("mapContainer"), {
            zoom: 13.5,
            center: { lat: 24.522383148639438, lng: 44.4186252342999 },
            mapTypeId: google.maps.MapTypeId.HYBRID ,
            disableDefaultUI: true, 
        });

        directionsRenderer.setMap(map);
        directionsRenderer.setPanel(document.getElementById("sidebar"));

  const control = document.getElementById("floating-panel");

  map.controls[google.maps.ControlPosition.TOP_CENTER].push(control);

        {% for x in stu %}
        document.getElementById({{x.id}}).addEventListener("click", () => {
            addr =' {{x.address}}'
      calculateAndDisplayRoute(directionsService, directionsRenderer , addr );
    });
    {% endfor %}
 
        


    }


    function calculateAndDisplayRoute(directionsService, directionsRenderer , addr) {
        directionsService
            .route({
                origin: {
                    query: document.getElementById("start").value,
                },
                destination: {
                    query: addr,
                },
                travelMode: google.maps.TravelMode.DRIVING,
                
            })
            .then((response) => {
                directionsRenderer.setDirections(response);
            })
            .catch((e) => window.alert("Directions request failed due to " + status));
    }

    window.initMap = initMap;

</script>

<section class="content ">
    <div class="block-header mt-6">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>App Widgets
                    <small>Welcome to Oreo</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <button class="btn btn-white btn-icon btn-round hidden-sm-down float-right m-l-10" type="button">
                    <i class="zmdi zmdi-plus"></i>
                </button>
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Oreo</a></li>
                    <li class="breadcrumb-item active">Widgets</li>
                    <li class="breadcrumb-item active">App</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <!-- start student list -->
        <div class="col-sm-12 col-md-12 col-lg-2">
            <div class="card current_progress">
                <div class="header">
                    <h2><strong>student</strong> list</small></h2>
                </div>

                <div class="body">
                    <div class="chat-widget">
                        <ul class="chat-scroll-list clearfix">
                            <li class="inbox-inner"> <a href="javascript:void(0)">
                                    <div class="inbox-item">

                                    </div>
                                </a>
                            </li>




                        </ul>
                        <ul class="chat-scroll-list clearfix">
                            <div class="body">
                                <ul class="list-unstyled activity">
                                    {% for x in stu %}
                                    <li id="{{ x.id }}">
                                        <a href="javascript:void(0)">
                                            <i class=""><img
                                                    src="{% if x.gender == 'girl' %} {% static 'assets/images/avatar_girl.jpeg' %}{% else %} {% static 'assets/images/avatar_boy.jpeg' %} {% endif %}"
                                                    class="rounded" style="width: 200px;" alt=""></i>
                                            <div class="info">
                                                <h6>{{x.name}} </h6>
                                                <small>{{x.gender |default:"--"}}</small>

                                            </div>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </ul>
                    </div>
                   
                </div>
            </div>
        </div>
        <!-- end student list -->
        <!-- start map -->
        <div class="col-sm-12 col-md-12 col-lg-10">
            <div class="card">
                <div class="header">
                    <h2><strong>Map</strong> Bus Trip</h2>
                  
                </div>
                <div class="body">
                   
                    <div class="row clearfix"> 
                        <div class="col-sm-12 col-md-12 col-lg-10">
                            <div id="mapContainer"></div>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-2">
                           
                                <div class="chat-widget">
                                    <ul class="chat-scroll-list clearfix">
                                        <div class="body " style="padding: 0%;">
                                            <ul class="list-unstyled activity">
                                                <div id="sidebar">
                                            </ul>
                                        </div>
                                    </ul>
                                </div>
                            
                        </div>

                    </div>
                      
                       
                            

                  
                </div>
            </div>
        </div>
        <!-- end map -->
    </div>
    <select id="start" style="visibility: hidden;">
        <option value="HF7F+PC7 جامعة شقراء, Al Rabwah, Al Duwadimi 17472" style="visibility: hidden;"></option>

    </select>

    
   
</section>

<!-- 
      The `defer` attribute causes the callback to execute after the full HTML
      document has been parsed. For non-blocking uses, avoiding race conditions,
      and consistent behavior across browsers, consider loading using Promises.
      See https://developers.google.com/maps/documentation/javascript/load-maps-js-api
      for more information.
      -->

<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCClagirEbcFsHwY7YipA6CeqEPyT7ciRo&callback=initMap&v=weekly&language=ar&region=SA"
    defer></script>

{% endblock content %}

home/templates/home/home.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<section class="content ">

    {% include 'home/include/block_header.html' %}
    {% include 'home/include/card_count.html' %}

    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script>

        $(document).ready(function () {
            $.ajax({
                url: "{% url 'home:mydata2'%}",
                method: 'GET',
                success: function (data) {
                    console.log(data);
                    initMap(data);
                }
            });
        });

        function initMap(data) {
            const map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12.5,
                center: { lat: 24.522383148639438, lng: 44.4186252342999 },
                mapTypeId: google.maps.MapTypeId.HYBRID
            });


            const image =
                "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png";
            const icon = {
                url: "https://cdn0.iconfinder.com/data/icons/small-n-flat/24/678111-map-marker-64.png", // url
                scaledSize: new google.maps.Size(50, 50), // scaled size
                origin: new google.maps.Point(0, 0), // origin
                anchor: new google.maps.Point(0, 0) // anchor
            };

            const markers = data?.map((i) => {

                const contentString =
                    '<div id="content">' +
                    '<div id="siteNotice">' +
                    '<h4 id="firstHeading" class="firstHeading">' + i.name + '</h4>' +
                    '<p id="firstHeading" class="firstHeading"><strong>Age  :</strong>' + i.age + '</p>' +
                    '<p id="firstHeading" class="firstHeading"> <strong>Gender  :</strong>' + i.gender + '</p>' +

                    "</div>" +
                    "</div>";






                const marker = new google.maps.Marker({
                    position: { lat: parseFloat(i.latitude), lng: parseFloat(i.longitude) },
                    map: map,
                    icon: icon,
                })


                const infowindow = new google.maps.InfoWindow({
                    content: contentString,
                    ariaLabel: "Uluru",
                });



                marker.addListener("click", () => {

                    infowindow.open({
                        anchor: marker,
                        map,

                    });
                });



                var place = document.getElementById(i.id);
                place.addEventListener("click", () => {

                    map.setZoom(16);

                    infowindow.open({
                        anchor: marker,
                        map,
                    });
                })



            });

        }
        function scrollToElement(id) {
            var elmnt = document.getElementById("content");
            elmnt.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    </script>



    <div class="row clearfix">
        <!-- start student list -->
        <div class="col-sm-12 col-md-12 col-lg-4">
            <div class="card current_progress">
                <div class="header">
                    <h2><strong>student</strong> list</small></h2>
                </div>

                <div class="body">
                    <div class="chat-widget" style="height: 500px; overflow: hidden; width: auto;">
                       
                        <ul class="chat-scroll-list clearfix">
                            <div class="body">
                                <ul class="list-unstyled activity">
                                    {% for x in stu %}
                                    <li id="{{ x.id }}" onclick="scrollToElement({{x.id}})">
                                        <a href="javascript:void(0)">
                                            <i class=""><img
                                                    src="{% if x.gender == 'girl' %} {% static 'assets/images/avatar_girl.jpeg' %}{% else %} {% static 'assets/images/avatar_boy.jpeg' %} {% endif %}"
                                                    class="rounded" style="width: 200px;" alt=""></i>
                                            <div class="info">
                                                <h4>{{x.name}} </h4>
                                                <small>{{x.address |default:"--"}}</small>

                                            </div>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </ul>
                    </div>
                 
                </div>
            </div>
        </div>
        <!-- end student list -->
        <!-- start map -->
        <div class="col-sm-12 col-md-12 col-lg-8">
            <div class="card">
                <div class="header">
                    <h2><strong>Map</strong> Api</h2>
                    <ul class="header-dropdown">
                        <li class="dropdown"> <a href="#gomap" class="dropdown-toggle" data-toggle="dropdown"
                                role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else</a></li>
                            </ul>
                        </li>
                        <li class="remove">
                            <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="body">
                        <div class="linkholder">
                            <div class="mapholder" id="gomap">
                                <div id="map"></div>
                                <script
                                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCClagirEbcFsHwY7YipA6CeqEPyT7ciRo&callback=initMap&v=weekly"
                                    defer></script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end map -->
    </div>


</section>


<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCClagirEbcFsHwY7YipA6CeqEPyT7ciRo&callback=initMap&v=weekly"
    defer></script>


{% endblock content %}