Bus_Pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('transporter/', include('transporter.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from .views import *
from django.urls import path, include
from . import views as view

#from transporter.views import Create_Schedule_Trips
app_name = 'home'
urlpatterns = [
   path('',view.home, name="index"),
   path('c/',Create_Schedule_Trips, name="index22"),
   path('Student_Location/',view.Student_Location, name="Student_Location"),
   path('mydata2/',view.mydata2, name="mydata2"),
  
  

]

transporter/urls.py
from .views import *
from django.urls import path, include
from . import views as view


app_name = 'transporter'
urlpatterns = [
   path('',view.index, name="index"),
   path('Schedule_School_To_Home/',view.Schedule_School_To_Home_View, name="Schedule_School_To_Home"),
   path('Schedule_Home_To_School/',view.Schedule_Home_To_School_View, name="Schedule_Home_To_School"),
   path('Driver_Directions_HomeToSchool/',view.Driver_Directions_HomeToSchool, name="Driver_Directions_HomeToSchool"),
   path('Driver_Directions_SchoolToHome/',view.Driver_Directions_SchoolToHome, name="Driver_Directions_SchoolToHome"),
   path('Set_Take_Time/', Set_Take_Time, name='Set_Take_Time'),
   path('Set_Leave_Time/', Set_Leave_Time, name='Set_Leave_Time'),
   path('Set_Leave_Time/', Set_Leave_Time, name='Set_Leave_Time'),
   path('Set_Not_Attend/', Set_Not_Attend, name='Set_Not_Attend'),
   path('start_trip/', start_trip, name='start_trip'),
   path('end_trip/', end_trip, name='end_trip'),
   path('Trips_Boked/<int:Trips_id>/',Trips_Boked,name='Trips_Boked') ,
   path('Driver_Map_Directions/<int:Trips_id>/',Driver_Map_Directions,name='Driver_Map_Directions') ,
   path('', index, name="inbox"), 
   path('video/', video, name="video"), 
   path('inbox/', inbox_view, name="inbox"), 
 

]

transporter/models.py
from django.db import models
from users.models import *
from home.models import *
from django.utils import timezone
from django.utils.timesince import timesince
from django.conf import settings
import uuid
from django.db.models.signals import post_save, post_delete





class Buses(models.Model):
    bus_no = models.CharField(max_length=255)
    Driver = models.OneToOneField(Profile, limit_choices_to={'role': 'Driver'},  on_delete=models.DO_NOTHING , related_name='Driver_Bus' , null=True , blank=True)
    Staff = models.OneToOneField(Profile, limit_choices_to={'role': 'Staff'},  on_delete=models.DO_NOTHING , related_name='Staff_Bus' , null=True , blank=True)
    def __str__(self):
        return str(self.bus_no)
    


class Seats(models.Model):
    bus_no = models.ForeignKey(Buses,  on_delete=models.DO_NOTHING , related_name='Bus')
    seat_id=models.CharField(max_length=10, unique=True)
    booked_to = models.OneToOneField(Student, limit_choices_to={'assign_seats': 'False'} ,  on_delete=models.DO_NOTHING , related_name='Student_seat' )
    
    def __str__(self):
        return str(self.seat_id)
    def save(self, *args, **kwargs):
        get_stu = Student.objects.get(id=self.booked_to.id)
        get_stu.assign_seats = True
        get_stu.save()
        return super().save(*args, **kwargs)

Trips_Type = (
			('Home_To_School', 'To School'),
			('School_To_Home', 'To Home'),
			)



Trips_Status = (
			('DELIVERED', 'DELIVERED'),
			('PENDING', 'PENDING'),
			('Not Yet', 'Not Yet'),
			)
class Type_Role(models.TextChoices):
        Home_To_School = "Home_To_School", "Home_To_School"
        School_To_Home = "School_To_Home", "School_To_Home" 

class Trips_Schedule(models.Model):
    
    base_role = Type_Role.Home_To_School
    Trips_Type = models.CharField(max_length=50, choices=Type_Role.choices , default=base_role)
    Trip_Date = models.DateField(auto_now=False , blank=True , null=True)
    Trips_Status = models.CharField(choices=Trips_Status, max_length=30 , default = 'Not Yet')
    Start_Time = models.TimeField(auto_now=False , blank=True , null=True)
    End_Time = models.TimeField(auto_now=False , blank=True , null=True)
    bus_no = models.ForeignKey(Buses,  on_delete=models.DO_NOTHING , related_name='Bus_Trips')
    
    def __str__(self):
        return str(self.Trips_Type)
    class Meta:
       unique_together = ('bus_no', 'Trip_Date')





class Schedule_Home_To_SchoolManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(Trips_Type=Type_Role.Home_To_School)


class Schedule_Home_To_School(Trips_Schedule):

    base_role = Type_Role.Home_To_School

    Home_To_School = Schedule_Home_To_SchoolManager()


    class Meta:
        proxy = True
        verbose_name_plural = " Home_To_School "  





class Schedule_School_To_Home(models.Manager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(Trips_Type=Type_Role.School_To_Home)


class Schedule_School_To_Home(Trips_Schedule):
    
    base_role = Type_Role.School_To_Home
    #Trips_Type = models.CharField(max_length=50, choices=Type_Role.choices , default=base_role)

    School_To_Home = Schedule_School_To_Home()


    class Meta:
        proxy = True
        verbose_name_plural = " School_To_Home "  














class Student_Bus_Status(models.TextChoices):
        Take_the_bus = "Take_the_bus", "Take_the_bus"
        Leave_the_bus = "Leave_the_bus", "Leave_the_bus" 
        Not_Attend = "Not_Attend", "Not_Attend" 






class Trips_Bus(models.Model):
    Trips_id = models.ForeignKey(Trips_Schedule,  on_delete=models.DO_NOTHING , related_name='Trips_Bus_id')
    Seat_Number = models.ForeignKey(Seats,  on_delete=models.DO_NOTHING , related_name='Trips_Seat_id', null=True , blank=True)
    Student_Name = models.ForeignKey(Student,  on_delete=models.DO_NOTHING , related_name='Trips_Student_id', null=True , blank=True)
    Student_Take_Time = models.TimeField(auto_now=False , blank=True , null=True)
    Student_Leave_Time = models.TimeField(auto_now=False , blank=True , null=True)
    Student_Bus_Status = models.CharField(max_length=50, choices=Student_Bus_Status.choices ,blank=True , null=True)


    class Meta:
       unique_together = [('Trips_id', 'Student_Name'), ('Trips_id', 'Seat_Number')]
   
   

# Create your models here.
class Guardians_Message(models.Model):
	message = models.TextField()
	From_User = models.ForeignKey(User, related_name='From_User' , on_delete=models.CASCADE)
	To_User = models.ForeignKey(User, related_name='To_user', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

class Comment(models.Model):
	comment = models.TextField()
	user = models.ForeignKey(User, related_name='usercomment' , on_delete=models.CASCADE)
	message = models.ForeignKey(Guardians_Message, related_name='messagecomment', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

transporter/views.py
from django.shortcuts import render , get_object_or_404
from django.http import JsonResponse
from datetime import timedelta, date
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from home.models import *
from django.shortcuts import get_object_or_404

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

    

def Create_Schedule_Trips(request):
    start_dt = date(2024,5,15)
    end_dt = date(2024,7,30)

    weekdays = [4,5]
    for dt in daterange(start_dt, end_dt):
        if dt.weekday() not in weekdays:

            Trips_Schedule.objects.create(Trips_Type = 'School_To_Home' , Trip_Date = dt , bus_no = Buses.objects.first())
           
    return render(request, 'transporter/Trips_Schedule.html' )



def index(request):
    
    ss = Trips_Schedule.objects.all()
    p = Paginator(ss, 5)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj}
    return render(request, 'transporter/Trips_Schedule.html' , context)





            

def Schedule_School_To_Home_View(request):
    get_role = request.user.profile.role
    
    if get_role == 'Staff':
        data = get_object_or_404(Buses, Staff= request.user.profile)
        #ss = Buses.objects.get_object_or_404(Staff__id = request.user.id )
        
        School_To_Home = Schedule_Home_To_School.objects.filter(bus_no = data ,  Trips_Type =  'School_To_Home')
    
    p = Paginator(School_To_Home, 10)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj}
    return render(request, 'transporter/Staff_School_To_Home.html' , context)

from datetime import datetime as dt

def Schedule_Home_To_School_View(request):
    get_role = request.user.profile
    
    
    data = get_object_or_404(Buses, Staff= request.user.profile)
        #ss = Buses.objects.get_object_or_404(Staff__id = request.user.id )
        
    Home_To_School = Schedule_Home_To_School.objects.filter(bus_no = data ,  Trips_Type =  'Home_To_School')
    
    
    p = Paginator(Home_To_School, 10)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj  , 'get_role':get_role}
    return render(request, 'transporter/Staff_Home_To_School.html' , context)

def Trips_Boked(request,Trips_id):
    Trips = get_object_or_404(Trips_Schedule,pk=Trips_id)
    Boked = Trips_Bus.objects.filter(Trips_id = Trips)
    context = {'Trips': Trips , 'Boked':Boked }
    return render(request, 'transporter/Trips_Bus.html' , context)


def video(request):

    

    return render(request, 'transporter/video.html')

import datetime


def  Set_Take_Time(request):
    id1 = request.GET.get('id', None)
    get_id = Trips_Bus.objects.get(id=id1)
    get_id.Student_Take_Time =datetime.datetime.now().time()
    get_id.Student_Bus_Status = 'Take_the_bus'
    get_id.save()
    data = {
        'Done': 'True'
        }
    return JsonResponse(data)

def  Set_Leave_Time(request):
    id1 = request.GET.get('id', None)
    get_id = Trips_Bus.objects.get(id=id1)
    get_id.Student_Leave_Time =datetime.datetime.now().time()
    get_id.Student_Bus_Status = 'Leave_the_bus'
    get_id.save()
    data = {
        'Done': 'True'
        }
    return JsonResponse(data)

def  Set_Not_Attend(request):
    id1 = request.GET.get('id', None)
    get_id = Trips_Bus.objects.get(id=id1)
    get_id.Student_Bus_Status = 'Not_Attend'
    get_id.Student_Leave_Time = None
    get_id.Student_Take_Time = None
    mobile_id = get_id.Student_Name.guardian_numbber
    
    get_id.save()
    data = {
        'Done': 'True'
        }
    number = str(mobile_id)
    name = 'nagib'
    text = number
    Send_SMS(text , name )
    
    print(number)
    return JsonResponse(data )


def  start_trip(request):
    id1 = request.GET.get('id', None)
    get_id = Trips_Schedule.objects.get(id=id1)
    get_id.Trips_Status = 'PENDING'
    get_id.save()
    data = {
        'Done': 'True'
        }
    return JsonResponse(data)





def  end_trip(request):
    id1 = request.GET.get('id', None)
    get_id = Trips_Schedule.objects.get(id=id1)
    get_id.Trips_Status = 'DELIVERED'
    get_id.save()
    data = {
        'Done': 'True'
        }
    return JsonResponse(data)


from home.SMS import *
def  end_sms():
   name = 'ngggg'
   text = '966563481855'
   Send_SMS(text , name )
   return JsonResponse('data', safe=False)

def Driver_Directions_HomeToSchool(request):
    get_role = request.user.profile.role
    
    
    ss = Buses.objects.get(Driver__id = request.user.profile.id)
    School_To_Home = Schedule_Home_To_School.objects.filter(bus_no__id = ss.id , Trips_Type =  'Home_To_School')
 
    p = Paginator(School_To_Home, 10)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj , 'stu':School_To_Home}
    return render(request, 'transporter/Driver_Home_To_School.html' , context)

def Driver_Directions_SchoolToHome(request):
    get_role = request.user.profile.role
    

    ss = Buses.objects.get(Driver__id = request.user.profile.id)
    School_To_Home = Trips_Schedule.objects.filter(bus_no__id = ss.id , Trips_Type =  'School_To_Home')
   
    p = Paginator(School_To_Home, 10)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj , 'stu':School_To_Home}
    return render(request, 'transporter/Driver_School_To_Home.html' , context)





def Driver_Map_Directions(request,Trips_id):
    Trips = get_object_or_404(Trips_Schedule,pk=Trips_id)
    stu = Trips_Bus.objects.filter(Trips_id = Trips , Student_Bus_Status = 'Take_the_bus')
    dd = stu.values('Student_Name')
    print(dd)
    
    ss = Student.objects.filter(id__in = dd )
    context = {'stu':ss }

    #stu = Student.objects.filter(id__in=trpbus.Student_Name.id)
    
    if Trips.Trips_Type == 'Home_To_School' :
        
        return render(request, 'transporter/Driver/Driver_Directions_HomeToSchool.html' , context)
    else :
        return render(request, 'transporter/Driver/Driver_Directions_SchoolToHome.html' , context)





def inbox_view(request , messges_id=None):
    my_messges = Guardians_Message.objects.filter(To_User=request.user)
   
    commit_list = Comment.objects.filter(user=request.user)
        
    context = {
        'my_msg': my_messges,
        'msg': commit_list ,
      
    }
    return render(request, 'transporter/inbox.html', context)

transporter/templates/transporter/Staff_Home_To_School.html
{% extends '_base.html' %} {% load static %} {% block content %}


<link rel="stylesheet" href="{% static 'assets/css/sweetalert.css' %}" />
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>
                    Trips Schedule List 
                 
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">

            </div>
        </div>
    </div>
    <div class="container-fluid">
        <!-- Hover Rows -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>Trips</strong> Schedule
                           
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                    role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="zmdi zmdi-more"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                        
                    </div>
                    <div class="body table-responsive">
                        {{request.user.Staff_Bus.bus_no}}
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>Trips Type</th>
                                    <th>Trip Day</th>
                                    <th>Trip Date</th>
                                    <th>bus no</th>
                                    <th>Status</th>
                                    <th >Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for x in page_obj.object_list %}
                                <tr>
                                    <th > <a >{{x.id}}</a></th>
                                    <td>{{x.Trips_Type}}</td>
                                    <td>{{x.Trip_Date |date:"l"}}</td>
                                    <td>{{x.Trip_Date |date:"Y-m-d"}}</td>
                                    <td>{{x.bus_no}}</td>
                                    <td>
                                        {% if x.Trips_Status == 'Not Yet' %}
                                        <span class="badge badge-info">{{x.Trips_Status}}</span>
                                        {% elif x.Trips_Status == 'PENDING' %}
                                        <span class="badge badge-warning">{{x.Trips_Status}}</span>
                                        {% elif x.Trips_Status == 'DELIVERED' %}
                                        <span class="badge badge-success">{{x.Trips_Status}}</span>

                                        {% endif %}
                                        
                                    </td>
                                    <td>
                                      
                                        <a href="{%url 'transporter:Trips_Boked' x.id %}" class="" >

                                            <i class="zmdi  zmdi-hc-2x zmdi-eye"><span>  </span></i>
                                        
                                            
                                            </a>
                                            <strong style="margin-left: 8px;margin-right: 8px;">|</strong>
                                           
                                             <button type="button" class="btn btn-icon btn-neutral btn-icon-mini " onClick="start_trip({{x.id}})" >
                                                <i class="zmdi zmdi-hc-2x zmdi-pin"><span></span></i>
                                            </button>
                                             <strong style="margin-left: 8px;margin-right: 8px;">|</strong>
                                          
                                             <strong style="margin-left: 8px;margin-right: 8px;">|</strong>
                                           
                                             <button type="button" class="btn btn-icon btn-neutral btn-icon-mini " onClick="end_trip({{x.id}})" >
                                                <i class="zmdi zmdi-hc-2x zmdi-pin-off"><span></span></i>
                                            </button>
                                      
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>


                {% include 'pagination.html' %}
              
            </div>
        </div>
        <!-- #END# Hover Rows -->
    </div>
</section>




<script>
   

    function start_trip(id) {
     swal({
         title: "Are you Started ?",
         
         type: "info",
         showCancelButton: true,
         closeOnConfirm: false,
         showLoaderOnConfirm: true,
     }, function () {
         $.ajax({
         url: '{% url "transporter:start_trip" %}',
         data: {
             'id': id,
         },
         dataType: 'json',
         success: function (data) {
             setTimeout(function () {
             swal("Student Done!" , "success");
             window.location.reload();
         }, 2000);
         }
     });
        
     });
 }
 

    function end_trip(id) {
     swal({
         title: "Are you Started ?",
         
         type: "info",
         showCancelButton: true,
         closeOnConfirm: false,
         showLoaderOnConfirm: true,
     }, function () {
         $.ajax({
         url: '{% url "transporter:end_trip" %}',
         data: {
             'id': id,
         },
         dataType: 'json',
         success: function (data) {
             setTimeout(function () {
             swal("Student Done!" , "success");
             window.location.reload();
         }, 2000);
         }
     });
        
     });
 }
 
 
 
 
 

 
 </script>
 <script src="{% static 'assets/js/sweetalert.min.js' %}"></script> <!-- SweetAlert Plugin Js --> 
 
 

{% endblock %}

transporter/templates/transporter/Staff_School_To_Home.html
{% extends '_base.html' %} {% load static %} {% block content %}
<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>
                    Trips Schedule List 
                 
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">

            </div>
        </div>
    </div>
    <div class="container-fluid">
        <!-- Hover Rows -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>Trips</strong> Schedule
                           
                        </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                    role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="zmdi zmdi-more"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                        
                    </div>
                    <div class="body table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>Trips Type</th>
                                    <th>Trip Day</th>
                                    <th>Trip Date</th>
                                    <th>bus no</th>
                                    <th>Status</th>
                                    <th >Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for x in page_obj.object_list %}
                                <tr>
                                    <th > {{x.id}}</th>
                                    <td>{{x.Trips_Type}}</td>
                                    <td>{{x.Trip_Date |date:"l"}}</td>
                                    <td>{{x.Trip_Date |date:"Y-m-d"}}</td>
                                    <td>{{x.bus_no}}</td>
                                    <td>
                                        {% if x.Trips_Status == 'Not Yet' %}
                                        <span class="badge badge-info">{{x.Trips_Status}}</span>
                                        {% elif x.Trips_Status == 'PENDING' %}
                                        <span class="badge badge-warning">{{x.Trips_Status}}</span>
                                        {% elif x.Trips_Status == 'DELIVERED' %}
                                        <span class="badge badge-success">{{x.Trips_Status}}</span>

                                        {% endif %}
                                        
                                    </td>
                                    <td>
                                      
                                        <a href="{%url 'transporter:Trips_Boked' x.id %}" class="" >

                                            <i class="zmdi zmdi-hc-2x zmdi-eye"><span></span></i>
                                        
                                            
                                            </a>
                                      
                                            <a href="{%url 'transporter:Driver_Map_Directions' x.id %}" class="" >

                                                <i class="zmdi zmdi-hc-2x zmdi-pin"><span> Start</span></i>
                                            
                                                
                                             </a>
                                          
                                            <a href="{%url 'transporter:Driver_Map_Directions' x.id %}" class="" >
    
                                                <i class="zmdi zmdi-hc-2x zmdi-pin off"><span>End</span></i>
                                            
                                                
                                             </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>


                {% include 'pagination.html' %}
              
            </div>
        </div>
        <!-- #END# Hover Rows -->
    </div>
</section>

{% endblock %}

transporter/templates/transporter/pagination.html
<div class="card">
    <div class="body">
      
        <ul class="pagination pagination-primary m-b-0">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="zmdi zmdi-arrow-left"></i></a></li>
            {% endif %}
            {% for num_pages in page_obj.paginator.page_range %}
            {% if page_obj.number == num_pages %}
            <li class="page-item active"><a class="page-link" href="javascript:void(0);">{{ num_pages }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num_pages }}">{{ num_pages }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="zmdi zmdi-arrow-right"></i></a></li>
            {% endif %}
        </ul>
    </div>
</div>

transporter/templates/transporter/video.html
{% extends '_base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'assets/css/chatapp.css' %}" />

<section class="content">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Stater Page
                <small>Welcome to Oreo</small>
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">                
                <button class="btn btn-white btn-icon btn-round hidden-sm-down float-right m-l-10" type="button">
                    <i class="zmdi zmdi-plus"></i>
                </button>
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Bus Pro</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">بشااااااااااير</a></li>
                    <li class="breadcrumb-item active">vid Page</li>
                </ul>                
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="body">
                        <li class="breadcrumb-item"><a href="javascript:void(0);">بشااااااااااير</a></li>
                    </div>
                    <video src="{% static 'assets/video/Bus_Camera.mp4' %}" muted autoplay loop playsinline></video>



                    <script>
                        window.addEventListener('load', async () => {
                      let video = document.querySelector('video[muted][autoplay]');
                      try {
                        await video.play();
                      } catch (err) {
                        video.controls = true;
                      }
                    });
                    </script>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}