Bus_Pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('transporter/', include('transporter.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from .views import *
from django.urls import path, include
from . import views as view

#from transporter.views import Create_Schedule_Trips
app_name = 'home'
urlpatterns = [
   path('',view.home, name="index"),
   path('c/',Create_Schedule_Trips, name="index22"),
   path('Student_Location/',view.Student_Location, name="Student_Location"),
   path('mydata2/',view.mydata2, name="mydata2"),
  
  

]

transporter/urls.py
from .views import *
from django.urls import path, include
from . import views as view


app_name = 'transporter'
urlpatterns = [
   path('',view.index, name="index"),
   path('Schedule_School_To_Home/',view.Schedule_School_To_Home_View, name="Schedule_School_To_Home"),
   path('Schedule_Home_To_School/',view.Schedule_Home_To_School_View, name="Schedule_Home_To_School"),
   path('Driver_Directions_HomeToSchool/',view.Driver_Directions_HomeToSchool, name="Driver_Directions_HomeToSchool"),
   path('Driver_Directions_SchoolToHome/',view.Driver_Directions_SchoolToHome, name="Driver_Directions_SchoolToHome"),
   path('Set_Take_Time/', Set_Take_Time, name='Set_Take_Time'),
   path('Set_Leave_Time/', Set_Leave_Time, name='Set_Leave_Time'),
   path('Set_Leave_Time/', Set_Leave_Time, name='Set_Leave_Time'),
   path('Set_Not_Attend/', Set_Not_Attend, name='Set_Not_Attend'),
   path('start_trip/', start_trip, name='start_trip'),
   path('end_trip/', end_trip, name='end_trip'),
   path('Trips_Boked/<int:Trips_id>/',Trips_Boked,name='Trips_Boked') ,
   path('Driver_Map_Directions/<int:Trips_id>/',Driver_Map_Directions,name='Driver_Map_Directions') ,
   path('', index, name="inbox"), 
   path('video/', video, name="video"), 
   path('inbox/', inbox_view, name="inbox"), 
 

]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'users'
urlpatterns = [
    path('', home, name='users-home'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', signup, name='register'),
    path('profile/', pro, name='user_profile'),
    path('Driver_Profile/', Driver_Profile_view, name='Driver_Profile'),
    path('settings/change_password/',auth_views.PasswordChangeView.as_view(template_name='users/change_password.html', success_url=reverse_lazy('users:password_change_done')),name='password_change'),
    path('settings/change_password/done/',auth_views.PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'),name='password_change_done'),

]

ROOT_DIR/templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="Student transportation bus monitoring system . ">
    <title>:: BUS :: PRO</title>
    <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
    <!-- Favicon-->
    <link rel="stylesheet" type="text/css" href="{% static 'google/main.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/map.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <script type="text/javascript" src="//kit.fontawesome.com/b68b3cc9f2.js?ver=5.2.4"></script>
    <script src="https://kit.fontawesome.com/f44bd2967c.js" crossorigin="anonymous"></script>

    {% block css %}


    {% endblock css %}

</head>

<body class="theme-orange">

    <!-- Top Bar -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="m-t-30"><img class="zmdi-hc-spin" src="{% static 'assets/images/logo2.jpg' %}" width="48"
                    height="48" alt="Oreo"></div>
            <p>Please wait...</p>
        </div>
    </div>

    <nav class="navbar p-l-5 p-r-5">
        <ul class="nav navbar-nav navbar-left">
            <li><a href="javascript:void(0);" class="ls-toggle-btn" data-close="true"><i class="zmdi zmdi-swap"></i></a>
            </li>
            <li>
                <div class="navbar-header">
                    <a href="javascript:void(0);" class="bars"></a>
                    <a class="navbar-brand" href="index.html"><span class="m-l-10"> </span></a>
                </div>
            </li>


              
        </ul>
    </nav>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% include 'left_sidebar2.html' %}
    <!-- Main Content -->

    {% block content %}


    {% endblock %}


    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">

        <div class="tab-content">
            <div class="tab-pane slideRight active" id="setting">
                <div class="slim_scroll">
                    <div class="card">
                        <h6>Skins</h6>
                        <ul class="choose-skin list-unstyled">
                            <li data-theme="purple" class="active">
                                <div class="purple"></div>
                            </li>
                            <li data-theme="PINK">
                                <div class="PINK"></div>
                            </li>
                            <li data-theme="cyan">
                                <div class="cyan"></div>
                            </li>
                            <li data-theme="green">
                                <div class="green"></div>
                            </li>
                            <li data-theme="orange">
                                <div class="orange"></div>
                            </li>
                            <li data-theme="blush">
                                <div class="blush"></div>
                            </li>
                        </ul>
                    </div>
                    <div class="card theme-light-dark">
                        <h6>Left Menu</h6>
                        <button class="t-light btn btn-default btn-simple btn-round btn-block">Light</button>
                        <button class="t-dark btn btn-default btn-round btn-block">Dark</button>
                        <button class="m_img_btn btn btn-primary btn-round btn-block">Sidebar Image</button>
                    </div>

                </div>
            </div>

        </div>
    </aside>

    <form id="frm_logout" method="post" action="{% url 'users:logout' %}" style="visibility: hidden;"> {% csrf_token %}
    </form>

    <!-- Jquery Core Js -->
    <script src="{% static 'assets/js/libscripts.bundle.js' %}"></script>
    <!-- Lib Scripts Plugin Js -->

    <!-- Lib Scripts Plugin Js -->
    <script src="{% static 'assets/js/vendorscripts.bundle.js' %}"></script>

    <!-- USA Map Js -->


    <script src="{% static 'assets/js/mainscripts.bundle.js' %}"></script>

    {% block js %}


    {% endblock js %}

</body>

</html>

ROOT_DIR/templates/left_sidebar.html
{% load static %}
<!-- Left Sidebar -->
<aside id="leftsidebar" class="sidebar">

    <div class="tab-content">
        <div class="tab-pane stretchRight active" id="dashboard">
            <div class="menu">
             
                <ul class="list">
                    <li>
                        <div class="user-info m-b-20 p-b-15">
                            <div class="image"><a href="{% url 'home:index' %}" class=" waves-effect waves-block"><img
                                        src="{% static 'assets/images/logo2.jpg' %}" class="rounded"></a></div>
                            <div class="detail">
                                <h4>Bus Pro</h4>

                            </div>


                        </div>
                    </li>
                    {%if user.is_authenticated%}
                    {% if user.is_superuser %}

                    <li class="active open"> <a href="{% url 'home:index' %}"><i
                                class="zmdi zmdi-hc-2x zmdi-home"></i><span>Dashboard</span></a>
                    </li>


                  
                    <li class="active open"> <a href="{% url 'transporter:video' %}"><i
                                class="zmdi zmdi-hc-2x zmdi-pin"></i><span>Bus Video Stream </span></a>
                    </li>
                    <li> <a href="/admin"><i class="zmdi zmdi-shield-security"></i><span>Admin </span></a>
                    </li>
                    {% endif %}
                 
                    {% if user.role == 'Staff' %}
                    <li> <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block"><i
                                class="zmdi zmdi-hc-5x zmdi-account-box"></i><span>Staff</span> </a>
                        <ul class="ml-menu" style="display: none;">
                            <li><a href="{% url 'transporter:Schedule_School_To_Home' %}"
                                    class=" waves-effect waves-block"> Schedule School To Home </a></li>
                            <li><a href="{% url 'transporter:Schedule_Home_To_School' %}"
                                    class=" waves-effect waves-block">Schedule Home To_School </a></li>
                            <li><a href="" class=" waves-effect waves-block">Massges </a></li>
                        </ul>
                    </li>
                    {% endif %}

                    {% if user.role == 'Driver' %}
                    <li> <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block"><i
                                class="zmdi zmdi-hc-5x zmdi-bus"></i><span>Driver</span> </a>
                        <ul class="ml-menu" style="display: none;">
                            <li><a href="{% url 'transporter:Driver_Directions_HomeToSchool' %}"
                                    class=" waves-effect waves-block">Home To School </a></li>
                            <li><a href="{% url 'transporter:Driver_Directions_SchoolToHome' %}"
                                    class=" waves-effect waves-block">School To Home </a></li>
                            <li><a href="" class=" waves-effect waves-block">Messges </a></li>
                            <li><a href="{% url 'users:driver-profile' %}" class=" waves-effect waves-block">Profile </a></li>
                        </ul>
                    </li>
                    {% endif %}
                

                

                    {% endif %}
                </ul>
             
            </div>
        </div>
    </div>
</aside>

ROOT_DIR/templates/left_sidebar2.html
<aside id="leftsidebar" class="sidebar">
    <ul class="nav nav-tabs">
        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#dashboard"><i
                    class="zmdi zmdi-home m-r-5"></i>Home</a></li>
        <li class="nav-item"><a class="nav-link " data-toggle="tab" href="#user"><i
                    class="zmdi zmdi-account m-r-5"></i>User</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane stretchRight " id="dashboard">
            <div class="menu">
                <div class="slimScrollDiv"
                    style="position: relative; overflow: hidden; width: auto; height: calc(-60px + 100vh);">
                    <ul class="list" style="overflow: hidden; width: auto; height: calc(-60px + 100vh);">
                        <li>
                            <div class="user-info">
                                <div class="image"><a href="profile.html" class=" waves-effect waves-block"><img
                                            src="{{ user.profile.avatar.url }}" alt="User"></a></div>
                                <div class="detail">
                                    <h4>{{user}}</h4>
                                    <small>{{user.profile.role}}</small>
                                </div>



                            </div>
                        </li>
                        {%if user.is_authenticated%}
                        {% if user.is_superuser %}
    
                        <li class="active open"> <a href="{% url 'home:index' %}"><i
                                    class="zmdi zmdi-hc-2x zmdi-home"></i><span>Dashboard</span></a>
                        </li>
    
    
                      
                        <li class="active open"> <a href="{% url 'transporter:video' %}"><i
                                    class="zmdi zmdi-hc-2x zmdi-pin"></i><span>Bus Video Stream </span></a>
                        </li>
                        <li> <a href="/admin"><i class="zmdi zmdi-shield-security"></i><span>Admin </span></a>
                        </li>
                        {% endif %}
                     
                        {% if user.profile.role == 'Staff' %}
                        <li> <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block"><i
                                    class="zmdi zmdi-hc-5x zmdi-account-box"></i><span>Staff</span> </a>
                            <ul class="ml-menu" style="display: none;">
                                <li><a href="{% url 'transporter:Schedule_School_To_Home' %}"
                                        class=" waves-effect waves-block"> Schedule School To Home </a></li>
                                <li><a href="{% url 'transporter:Schedule_Home_To_School' %}"
                                        class=" waves-effect waves-block">Schedule Home To_School </a></li>
                                <li><a href="" class=" waves-effect waves-block">Massges </a></li>
                            </ul>
                        </li>
                        {% endif %}
    
                        {% if user.profile.role == 'Driver' %}
                        <li> <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block"><i
                                    class="zmdi zmdi-hc-5x zmdi-bus"></i><span>Driver</span> </a>
                            <ul class="ml-menu" style="display: none;">
                                <li><a href="{% url 'transporter:Driver_Directions_HomeToSchool' %}"
                                        class=" waves-effect waves-block">Home To School </a></li>
                                <li><a href="{% url 'transporter:Driver_Directions_SchoolToHome' %}"
                                        class=" waves-effect waves-block">School To Home </a></li>
                                <li><a href="" class=" waves-effect waves-block">Messges </a></li>
                             
                            </ul>
                        </li>
                        {% endif %}
                    
    
                    
    
                        {% endif %}
                    </ul>
                    <div class="slimScrollBar"
                        style="background: rgba(0, 0, 0, 0.2); width: 2px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 3px; z-index: 99; left: 1px; height: 233.469px;">
                    </div>
                    <div class="slimScrollRail"
                        style="width: 2px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 0px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; left: 1px;">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane stretchLeft active" id="user">
            <div class="menu">
                <div class="slimScrollDiv"
                    style="position: relative; overflow: hidden; width: auto; height: calc(-60px + 100vh);">
                    <ul class="list" style="overflow: hidden; width: auto; height: calc(-60px + 100vh);">
                        <li>
                            <div class="user-info m-b-20 p-b-15">
                                <div class="image"><a href="profile.html" class=" waves-effect waves-block"><img
                                            src="{{ user.profile.avatar.url }}" alt="User"></a></div>
                                <div class="detail">
                                    <h4>{{user}}</h4>
                                    <small>{{user.profile.role}}</small>
                                </div>


                            </div>
                        </li>
                        <li>

                            <ul class="list-unstyled">

                                <li class="active "> <a href="{% url 'users:user_profile' %}"><i
                                    class="zmdi zmdi-hc-2x zmdi-account-box-o"></i><span>Update Profile </span></a>
                                </li>

                                <li class="active "> <a href="{% url 'users:password_change' %}"><i
                                    class="zmdi zmdi-hc-2x zmdi-key"></i><span>Change Password </span></a>
                                </li>
                                <li><a href="javascript:$('#frm_logout').submit();" class=" waves-effect waves-block">logout </a></li>
                                {% if user.profile.role == 'Driver' %}
                                <li class="active "> <a href="{% url 'users:Driver_Profile' %}"><i
                                    class="zmdi zmdi-hc-3x zmdi-card"></i><span>driver license details  </span></a>
                                </li>
                                {% endif %}



                            </ul>
                        </li>
                    </ul>
                    <div class="slimScrollBar"
                        style="background: rgba(0, 0, 0, 0.2); width: 2px; position: absolute; top: 186px; opacity: 0.4; display: none; border-radius: 3px; z-index: 99; left: 1px; height: 141.628px;">
                    </div>
                    <div class="slimScrollRail"
                        style="width: 2px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 0px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; left: 1px;">
                    </div>
                </div>
            </div>
        </div>
    </div>
</aside>

ROOT_DIR/templates/pagination.html
<div class="card">
    <div class="body">
      
        <ul class="pagination pagination-primary m-b-0">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="zmdi zmdi-arrow-left"></i></a></li>
            {% endif %}
            {% for num_pages in page_obj.paginator.page_range %}
            {% if page_obj.number == num_pages %}
            <li class="page-item active"><a class="page-link" href="javascript:void(0);">{{ num_pages }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num_pages }}">{{ num_pages }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="zmdi zmdi-arrow-right"></i></a></li>
            {% endif %}
        </ul>
    </div>
</div>