Bus_Pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
    path('transporter/', include('transporter.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from .views import *
from django.urls import path, include
from . import views as view

#from transporter.views import Create_Schedule_Trips
app_name = 'home'
urlpatterns = [
   path('',view.home, name="index"),
   path('c/',Create_Schedule_Trips, name="index22"),
   path('Student_Location/',view.Student_Location, name="Student_Location"),
   path('mydata2/',view.mydata2, name="mydata2"),
  
  

]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'users'
urlpatterns = [
    path('', home, name='users-home'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', signup, name='register'),
    path('profile/', pro, name='user_profile'),
    path('Driver_Profile/', Driver_Profile_view, name='Driver_Profile'),
    path('settings/change_password/',auth_views.PasswordChangeView.as_view(template_name='users/change_password.html', success_url=reverse_lazy('users:password_change_done')),name='password_change'),
    path('settings/change_password/done/',auth_views.PasswordChangeDoneView.as_view(template_name='users/change_password_done.html'),name='password_change_done'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser , BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.staticfiles import *
from django.conf import settings
from PIL import Image
from .validators import *
from phonenumber_field.modelfields import PhoneNumberField

class User(AbstractUser):
    
    class Meta:
        permissions = (
            ("client", "Client"),
            ("support", "Support"),
        )


def Path_Profile_Avatar(instance,filename):
    

    return "media/Tourism/%s/Users/avataer/%s/avatar.jpeg"%(instance.user.username ,instance.user.username)

   

gender = (
        ('Male','Male'),
        ('Female','Female')
      
    )   



 
blood_type = (
        ('O+','O+'),
        ('B+','B+'),
        ('B-','B-'),
        ('AB+','AB+'),
        ('AB-','AB-'),
        ('A-','A-'),
        ('A+','A+'),
      
    )   

# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    class Role(models.TextChoices):
        Staff = "Staff", "Staff" # مشرف
        Guardian = "Guardian", "Guardian" # ولي أمر 
        Driver = "Driver", "Driver" # سائق حافله
        MEMBERS = "MEMBERS", "Members"
    base_role = Role.MEMBERS
    role = models.CharField(max_length=50, choices=Role.choices , default=base_role)
    user = models.OneToOneField(User, on_delete=models.CASCADE , related_name='profile')
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    Gender = models.CharField(choices=gender, default = 'Male' , max_length=10)
    Mobile_No = PhoneNumberField(help_text= 'EXP : 966563481855' ,blank=True , null=True , default='966563481855')

    def __str__(self):
        return self.user.username




class Driver_Profile(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE , related_name='Driver_Profile' , limit_choices_to={'role': 'Driver'})
    Blood_Type = models.CharField(choices=blood_type, default = 'O+' , max_length=10)
    license_Number = models.CharField(max_length=10 , blank=True, null=True)
    license_Expire_Date = models.DateField(validators=[validate_license_Expire] , blank=True, null=True)
    
    
    def __str__(self):
        return str(self.profile)
    class Meta:
     
        verbose_name_plural = "Driver Profile"  


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_profile, sender=User)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()



class GuardianManager(Profile):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(role=Profile.Role.Guardian)


class Guardians(Profile):

    base_role = Profile.Role.Guardian

    Guardian = GuardianManager()

    class Meta:
        proxy = True
        verbose_name_plural = " Students Guardians"  

users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import *





class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=255,required=True,widget=forms.EmailInput())

    class Meta:
        model=User
        fields = {'username','email','password1','password2'}
        
        
    

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

from django.forms.widgets import CheckboxSelectMultiple, RadioSelect



class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
   
    class Meta:
        model = Profile
        fields = ['avatar', 'Mobile_No' , 'Gender']


class UpdateDriver_ProfileForm(forms.ModelForm):
     
    bloodtype = (
            ('O+','O+'),
            ('B+','B+'),
            ('B-','B-'),
            ('AB+','AB+'),
            ('AB-','AB-'),
            ('A-','A-'),
            ('A+','A+'),
        
        ) 
    Blood_Type = forms.ChoiceField(required=False,
                                     widget=RadioSelect(),
                                     choices=bloodtype)
    class Meta:
        model = Driver_Profile
        fields = ['Blood_Type', 'license_Number' , 'license_Expire_Date']
       

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from .forms import *

@login_required
def home(request):
    return render(request, 'users/home.html')

def signup(request):
    form = SignUpForm()
    if request.method =='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('users:user_profile')

    return render(request,'users/register.html',{'form':form})

class RegisterView(View):
    form_class = SignUpForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})


# Class based view that extends from the built in login view to add a remember me functionality
class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users-home')


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('users-home')


@login_required
def profile(request):
    if request.method == 'POST':
        
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        
        avatar = request.FILES['avatar']
        print(avatar)
        if profile_form.is_valid():
           
            profile = profile_form.save(commit=False)
            profile.avatar = request.FILES['avatar']
            profile.save()
         
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users-profile')
    else:
        
        profile_form = UpdateProfileForm( instance=request.user.profile)

    return render(request, 'users/profile.html', { 'profile_form': profile_form})


def pro(request):

    if request.method == 'POST':
        form = UpdateProfileForm(request.POST, request.FILES , instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect(to='users:user_profile')

    else:
        form = UpdateProfileForm()

    return render(request, "users/profile.html", {'profile_form': form})



def Driver_Profile_view(request):

    if request.method == 'POST':
        form = UpdateDriver_ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect(to='users:user_profile')

    else:
        form = UpdateDriver_ProfileForm()

    return render(request, "users/Driver_Profile.html", {'Driver_form': form})










from django.contrib.auth import logout
from django.contrib.auth import logout
def logout_view(request):
    logout(request)
    return redirect('home:index')

users/templates/users/change_password_done.html
{% extends "_base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row r">
                <div class="col-lg-5">
                        <div class="card s">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                          

                            <div class="card-body">
                               Password is changed
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/form.html
<div class="body">
    {% if user_form.errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <div id="form_errors">
            {% for key, value in user_form.errors.items %}
            <strong>{{ value }}</strong>
            {% endfor %}
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row clearfix">
            {% for field in form %}
            <div class="col-md-6">


                <div class="input-group ">
                    <b> {{ field.name }} :</b><br>
                    {{ field }}
                    {% if field.errors %}
                <label class="error" style="color: red;" >{{ field.errors.as_text }}</label>
                {% endif %}
                </div>
                
            </div>
            {% endfor %}
        </div>


        <button class="btn btn-info btn-round">Save Changes</button>
    </form>

</div>

users/templates/users/login.html
{% load static %}

<!doctype html>
<html class="no-js " lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <meta name="description" content="Student transportation bus monitoring system . ">
        <title>:: BUS :: PRO</title>
        <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
        <!-- Favicon-->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/authentication.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}">
    </head>

<body class="theme-orange authentication sidebar-collapse">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent">
    <div class="container">        
        <div class="navbar-translate n_logo">
            <a class="navbar-brand" href="javascript:void(0);" title="" target="_blank">BUS PRO</a>
            <button class="navbar-toggler" type="button">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="">Home</a>
                </li>
              
               
                <li class="nav-item">
                    <a class="nav-link btn btn-white btn-round" href="{%url 'users:register'%}">SIGN UP</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<style>
    
</style>
<!-- End Navbar -->
<div class="page-header">
    
    <div class="container">
        <div class="col-md-12 content-center">
            <div class="col-lg-6 col-md-8 col-12 mx-auto ">
                <div class="card z-index-0 fadeIn3 fadeInBottom">
                 
                    <div class="card-body">
                        <form class="form" method="post" action="{%url 'users:login'%}?next={%url 'home:index'%}" >
                            {% csrf_token %}
                            <div class="header">
                                <div class="logo-container">
                                    <img src="{% static 'assets/images/login_logo.png' %}"  alt="">
                                </div>
                                <h5>Sign IN</h5>
                                <span></span>
                            </div>
                            <div class="content"> 
                                                           
                                <div class="input-group">
                                    <input type="text" class="form-control" name="{{ form.username.name }}" placeholder="Enter User Name">
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-account-circle"></i>
                                    </span>
                                    {% if form.username.errors %}
                                    <label class="error" style="color: red;" >{{ form.username.errors.as_text }}</label>
                                    {% endif %}
                                </div>
                                <div class="input-group">
                                    <input type="password" placeholder="Password" name="{{ form.password.name }}" class="form-control" />
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-lock"></i>
                                    </span>
                                </div>                        
                                                
                            </div>
        
                            <div class="footer text-center">
                                <button type="submit"  class="btn btn-primary btn-round btn-lg btn-block ">SIGN IN</button>
        
                              
                            </div>
                        </form>
                        <p class="" style="color: black;">Don't have an account? <a href="{% url 'users:register' %}">Sign up</a></p>
                    </div>
                </div>
            </div>
          
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <nav>
                <ul>
                    <li><a href="" target="_blank">Contact Us</a></li>
                    <li><a href="" target="_blank">About Us</a></li>
                    <li><a href="javascript:void(0);">FAQ</a></li>
                </ul>
            </nav>
            <div class="copyright">
                &copy;
                <script>
                    document.write(new Date().getFullYear())
                </script>,
                <span>Designed by <a href="" >Nageeb</a></span>
            </div>
        </div>
    </footer>
</div>


<!-- Jquery Core Js -->
<script src="{% static 'assets/js/libscripts.bundle.js'%}"></script>
<script src="{% static 'assets/js/vendorscripts.bundle.js'%}"></script> <!-- Lib Scripts Plugin Js --> 
<script>
    $(".navbar-toggler").on('click',function() {
     $("html").toggleClass("nav-open");
 });
 //=============================================================================
 $('.form-control').on("focus", function() {
     $(this).parent('.input-group').addClass("input-group-focus");
 }).on("blur", function() {
     $(this).parent(".input-group").removeClass("input-group-focus");
 });
 </script>
</body>
</html>

users/templates/users/password_reset.html
{% extends "_base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                        	<div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users-register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

users/templates/users/register.html
{% load static %}

<!doctype html>
<html class="no-js " lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <meta name="description" content="Student transportation bus monitoring system . ">
        <title>:: BUS :: PRO</title>
        <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
        <!-- Favicon-->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/authentication.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}">
    </head>

<body class="theme-orange authentication sidebar-collapse">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent">
    <div class="container">        
        <div class="navbar-translate n_logo">
            <a class="navbar-brand" href="javascript:void(0);" title="" target="_blank">BUS PRO</a>
            <button class="navbar-toggler" type="button">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="">Home</a>
                </li>
              
               
                <li class="nav-item">
                    <a class="nav-link btn btn-white btn-round" href="{%url 'users:register'%}">SIGN UP</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<style>
    
</style>
<!-- End Navbar -->
<div class="page-header">
    
    <div class="container">
        <div class="col-md-12 content-center">
            <div class="col-lg-6 col-md-8 col-12 mx-auto ">
                <div class="card z-index-0 fadeIn3 fadeInBottom">
                 
                    <div class="card-body">
                        <form class="form" method="post" action="{%url 'users:register'%}">
                            {% csrf_token %}
                            
                            <div class="content"> 
                               
                                <div class="input-group">
                                    <input type="text" class="form-control" name="{{ form.username.name }}" placeholder=" User Name">
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-account-circle"></i>
                                    </span>
                                    {% if form.username.errors %}
                                    <label class="error" style="color: red;" >{{ form.username.errors.as_text }}</label>
                                    {% endif %}
                                </div>
                                <div class="input-group">
                                    <input type="email" class="form-control" name="{{ form.email.name }}" placeholder=" Email">
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-email"></i>
                                    </span>
                                    {% if form.email.errors %}
                                    <label class="error" style="color: red;" >{{ form.email.errors.as_text }}</label>
                                    {% endif %}
                                </div>
                                <div class="input-group">
                                    <input type="password" placeholder="Password1" name="{{ form.password1.name }}" class="form-control" />
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-lock"></i>
                                    </span>
                                </div>                        
                                <div class="input-group">
                                    <input type="password" placeholder="Password2" name="{{ form.password2.name }}" class="form-control" />
                                    <span class="input-group-addon">
                                        <i class="zmdi zmdi-lock"></i>
                                    </span>
                                </div>                        
                            </div>
                            <div class="checkbox">
                                    <input id="terms" type="checkbox">
                                    <label for="terms" style="color: black;">
                                            I read and agree to the <a href="javascript:void(0);">terms of usage</a>
                                    </label>
                                </div>
                            <div class="footer text-c">
                                <button type="submit"  class="btn btn-primary btn-round btn-lg btn-block ">SIGN UP</button>
                            </div>
                        </form>
                        <p class="" style="color: black;">already an account <a href="{% url 'users:login' %}"> Login</a></p>
                    </div>
                </div>
            </div>
          
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <nav>
                <ul>
                    <li><a href="" target="_blank">Contact Us</a></li>
                    <li><a href="" target="_blank">About Us</a></li>
                    <li><a href="javascript:void(0);">FAQ</a></li>
                </ul>
            </nav>
            <div class="copyright">
                &copy;
                <script>
                    document.write(new Date().getFullYear())
                </script>,
                <span>Designed by <a href="" >Nageeb</a></span>
            </div>
        </div>
    </footer>
</div>


<!-- Jquery Core Js -->
<script src="{% static 'assets/js/libscripts.bundle.js'%}"></script>
<script src="{% static 'assets/js/vendorscripts.bundle.js'%}"></script> <!-- Lib Scripts Plugin Js --> 
<script>
    $(".navbar-toggler").on('click',function() {
     $("html").toggleClass("nav-open");
 });
 //=============================================================================
 
 </script>
</body>
</html>